rbp:
  name:                 'rails_best_practices'
  weight:               0.5
  command:              'rails_best_practices --without-color .'
  score_pattern:        'Found (\d+) error'
  problem_pattern:      '^\S.+:\d+.+$'
  line_number_pattern:  '^.+:(\d+)'
  filename_pattern:     '^\.\/(.+):\d'
  description_pattern:  '\s-\s(.+)$'
  
cleanup:
  name:                 'cleanup'
  weight:               5
  command:              "grep -r -n '#CLEANUP:' app/controllers app/helpers app/models lib"
  problem_pattern:      '^\S.+:\d+.+$'
  line_number_pattern:  '^.+:(\d+)'
  filename_pattern:     '^(.+):\d'
  description_pattern:  '#CLEANUP:\s(.+)$'

reek:
  name:                 'reek'
  weight:               1
  command:              "reek -y app/controllers app/helpers app/models lib"
  problem_pattern:      '!([^!]+)'
  line_number_pattern:  '- (\d+)'
  filename_pattern:     'source:\s(.+)$'
  description_pattern:  'message:\s(.+)$'

flog:
  name:                 'flog'
  weight:               1
  command:              'flog -s --continue app/controllers app/helpers app/models lib'
  score_pattern:        '([\d\.]+): flog\/method average'